name: connect-publish
on:
  push:
    branches: [master]

jobs:
  test-app:
    uses: ./.github/workflows/test-actions.yaml
  connect-publish:
    name: connect-publish
    needs: [test-app]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Connect content
        uses: rstudio/actions/connect-publish@main
        with:
          url: https://colorado.rstudio.com/rsc/
          api-key: ${{ secrets.CONNECT_API_KEY }}
          access-type: acl
          dir: |
            .:/shiny-workshop-test-prod-2